# Matriks

Matriks adalah susunan atau tata letak angka-angka dalam bentuk persegi panjang.Setiap angka dalam matriks disebut elemen matriks, elemen matriks biasanya memiliki baris dan kolom contoh matriks :


$$

C = \left[ \begin{array}{rrrr} 1 & 0 & 2 & -1 \\ 3 & 1 & -3 & 2 \\ 2 & 0 & 4 & 4 \\ 2 & 1 & -1 & -1 \end{array}\

$$



---

## Ajabar Matriks

Aljabar matriks melibatkan berbagai operasi, termasuk penjumlahan, pengurangan, dan perkalian terhadap matriks.



## Operasi Penjumlahan Matriks

Penjumlahan matriks adalah operasi antara dua matriks yang memiliki dimensi yang sama, yaitu jumlah baris dan kolomnya harus sama.
Contoh:

$$
\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 2 \\ 3 & 4  \\ \end{array}\right]
B = \left[ \begin{array}{rrrr} 5 & 6 \\ 7 & 8  \\ \end{array}\right]
\end{split}
$$

Untuk menjumlahkan matriks 𝑨 dan 𝐵, kita cukup menambahkan setiap elemen yang berada pada posisi yang sama. Jadi, hasil penjumlahan matriks adalah:

$$
\begin{split}
A + B = \left[ \begin{array}{rrrr} 1+5 & 2+6 \\ 3+7 & 4+8 \\ \end{array}\right]
\end{split}
$$


---
$$
\begin{split}
Hasil = \left[ \begin{array}{rrrr} 6 & 8 \\ 10 & 12  \\ \end{array}\right]
\end{split}
$$



In [ ]:
# Code Penjumlahan Matriks
import numpy as np
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))

hasil = a + b
print(a)
print()
print(b)
print()
print("hasil")
print(hasil)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

hasil
[[ 6  8]
 [10 12]]


## Operasi Pengurangan Matriks


Operasi pengurangan matriks adakah antara dua matriks yang memiliki dimensi yang sama, yaitu jumlah baris dan kolomnya identik. Operasi ini dilakukan dengan mengurangkan setiap elemen yang sesuai dari matriks pertama dengan matriks kedua. contoh:

$$
\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 2 \\ 3 & 4  \\ \end{array}\right]
B = \left[ \begin{array}{rrrr} 5 & 6 \\ 7 & 8  \\ \end{array}\right]
\end{split}
$$


Untuk mengurangkan matriks 𝑨 dari 𝐵, kita cukup mengurangkan setiap elemen yang berada pada posisi yang sama. Jadi, hasil pengurangan matriks adalah:

$$
\begin{split}
A - B = \left[ \begin{array}{rrrr} 1-5 & 2-6 \\ 3-7 & 4-8 \\ \end{array}\right]
\end{split}
$$

---

$$
\begin{split}
Hasil = \left[ \begin{array}{rrrr} -4 & -4 \\ -4 & -4  \\ \end{array}\right]
\end{split}
$$



In [ ]:
# Code Penjumlahan Matriks
import numpy as np
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))

hasil = a - b
print(a)
print()
print(b)
print()
print("hasil :")
print(hasil)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

hasil :
[[-4 -4]
 [-4 -4]]


## Operasi Perkalian Matriks

Operasi perkalian matriks adalah operasi antara dua matriks yang memiliki dimensi yang memenuhi aturan perkalian matriks. Aturan ini menyatakan bahwa jumlah kolom dari matriks pertama harus sama dengan jumlah baris dari matriks kedua. Contoh :

$$
\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 2 \\ 3 & 4  \\ \end{array}\right]
B = \left[ \begin{array}{rrrr} 5 & 6 \\ 7 & 8  \\ \end{array}\right]
\end{split}
$$

Untuk melakukan perkalian matriks 𝑨 dengan 𝐵, kita mengalikan setiap baris dari matriks 𝑨 dengan setiap kolom dari matriks 𝐵 dan menjumlahkan hasilnya.
Maka, hasil perkalian matriks 𝑨 dengan 𝐵 adalah:

$$
\begin{split}
A × B = \left[ \begin{array}{rrrr} (1 \times 5 + 2 \times 7) & (1 \times 6 + 2 \times 8) \\ (3 \times 5 + 4 \times 7) & (3 \times 6 + 4 \times 8) \\ \end{array}\right]
\end{split}
$$

---

$$
\begin{split}
Hasil = \left[ \begin{array}{rrrr} 19 & 22 \\ 43 & 50   \\ \end{array}\right]
\end{split}
$$


**Note : bahwa perkalian matriks tidak bersifat komutatif, artinya 𝑨 tidak selalu sama dengan 𝐵𝑨, kecuali jika kedua matriks tersebut merupakan matriks persegi dan memenuhi sifat-sifat tertentu.**

In [ ]:
# Code Perkalian Matriks
import numpy as np
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
b = np.array(([9,8,7],[6,5,4],[3,2,1]))

hasil = a @ b
print(a)
print()
print(b)
print()
print("hasil :")
print(hasil)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

hasil :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Tranpose Matriks

Transpose matriks adalah operasi yang menghasilkan matriks baru dengan menukar posisi baris dan kolom dari matriks asal. Dalam operasi ini, elemen-elemen yang terletak pada baris dipindahkan ke kolom, dan elemen-elemen yang ada di kolom dipindahkan baris. Contoh :

$$
\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 2 & 3 \\ 4 & 5 & 6 \\ \end{array}\right]
\end{split}
$$


Maka, transpose dari matriks 𝐴 adalah:

$$
\begin{split}
Aᵀ = \left[ \begin{array} {rrrr}1 & 4 \\ 2 & 5 \\ 3 & 6  \\ \end{array}\right]
\end{split}
$$


Jadi, matriks Aᵀ adalah hasil dari melakukan transpose terhadap matriks 𝐴, yaitu dengan menukar posisi baris dan kolomnya.


In [ ]:
# Code Tranpose Matriks

def trans(a):
  b = a.transpose()
  cova = b
  return b

a = np.array([[1,2,3],[4,5,6]])

print('matriks sebelum di transpose')
print(a)
print("\n")
print('matriks sesudah di transpose')
print(trans(a))

matriks sebelum di transpose
[[1 2 3]
 [4 5 6]]


matriks sesudah di transpose
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Code Perkalian Matriks tanpa Numpy

def perkalian_matriks(matriks1, matriks2):
    # Mendapatkan jumlah baris dan kolom untuk masing-masing matriks
    baris1 = len(matriks1)
    kolom1 = len(matriks1[0])
    baris2 = len(matriks2)
    kolom2 = len(matriks2[0])

    # Membuat matriks hasil dengan ukuran yang sesuai
    hasil = [[0 for _ in range(kolom2)] for _ in range(baris1)]

    # Melakukan perkalian matriks
    for i in range(baris1):
        for j in range(kolom2):
            for k in range(kolom1):
                hasil[i][j] += matriks1[i][k] * matriks2[k][j]

    return hasil

# Contoh matriks
matriks1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

matriks2 = [
     [9,8, 7],
     [6, 5, 4],
     [3, 2, 1],
]

# Memanggil fungsi perkalian_matriks untuk melakukan perkalian matriks
hasil_perkalian = perkalian_matriks(matriks1, matriks2)

# Menampilkan matriks asli dan hasil perkalian
print("Matriks Pertama:")
for baris in matriks1:
    print(baris)

print("\nMatriks Kedua:")
for baris in matriks2:
    print(baris)

print("\nHasil Perkalian Matriks:")
for baris in hasil_perkalian:
    print(baris)

Matriks Pertama:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matriks Kedua:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Hasil Perkalian Matriks:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]
