# Determinan



*   Buat fungsi mencari Determinan Matriks
*   Sifat sifat Determinan Matriks



In [4]:
import numpy as np

a = np.array([[3,4],[2,1,]])
b = np.array([[1,0,0],[0,1,0],[0,0,1]])
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
h = np.array([[6,8],[4,2]])
i = np.array([[6,8],[2,1]])
j = np.array([[6,4],[4,1]])
k = np.array([[4,1],[2,1]])
l = np.array([[7,5],[2,1]])
upper = np.array([[1,2,3],[0,1,2,],[0,0,1]])
lower = np.array([[1,0,0],[1,2,0],[1,2,3]])
aaa = np.array([[2,1],[1,1]])
bbb = np.array([[1,1],[1,1]])
ccc =  aaa@bbb


##1. Jika terdapat Matriks Identitas maka Determinannya adalah 1 berapapun ordonya




In [5]:
print("Matriks A :")
print(b)

det = np.linalg.det(b)
print(f"Determinan dari Matriks A : {int(det.round())}")

Matriks A :
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinan dari Matriks A : 1


##2. Jika salah satu baris diubah nilai elemennya maka hasil determinannnya juga ikut berubah

In [6]:
print("Matriks B :")
print(c)
det = np.linalg.det(c)
print(f"Determinan dari Matriks B : {int(det.round())}")


print("\n")
print("Matriks C :")
print(d)
detc = np.linalg.det(d)
print(f"Determinan dari Matriks C : {int(detc.round())}")

Matriks B :
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Determinan dari Matriks B : -3


Matriks C :
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinan dari Matriks C : 3


## 3.  Jika suatu baris ataupun kolom merupakan kelipatan dari baris atau kolom yang lain maka determinan matrix tersebut adalah 0 (baris 2 adalah kelipatan dari baris 1)

In [7]:
print("Matriks D :")
print(e)
det = np.linalg.det(e)
print(f"Determinan dari Matriks D : {int(det.round())}")


print("\n")
print("Matriks E :")
print(f)
detc = np.linalg.det(f)
print(f"Determinan dari Matriks E : {int(detc.round())}")

Matriks D :
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Determinan dari Matriks D : 0


Matriks E :
[[1 2 1]
 [2 4 2]
 [2 4 3]]
Determinan dari Matriks E : 0


## 4. Jika matrix tersebut adalah kelipatan sebanyak n * matrix maka untuk mencari determinan adalah (n^(sebanyak ordo)determinan matrix)contoh matrix g adalah kelipatan 2 kali dari matrix d

In [8]:
print("Matriks D :")
print(d)
det = np.linalg.det(d)
print(f"Determinan dari Matriks D : {int(det.round())}")


print("\n")
print("Matriks G :")
print(g)
detc = np.linalg.det(g)
print(f"Determinan dari Matriks G : {int(detc.round())}")

Matriks D :
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinan dari Matriks D : 3


Matriks G :
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinan dari Matriks G : 24



$$
Simulasi : 2^3(3) = 6*3 = 24
$$


Contoh dengan ordo 2x2

In [9]:
print("Matriks A :")
print(a)
det = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(det.round())}")


print("\n")
print("Matriks G :")
print(h)
detc = np.linalg.det(h)
print(f"Determinan dari Matriks H : {int(detc.round())}")


Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


Matriks G :
[[6 8]
 [4 2]]
Determinan dari Matriks H : -20



$$
Simulasi : 2^2(-5) = 4*(-5) = -20
$$


##5. Jika terdapat matrix baru dengan nilai salah satu baris atau kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2*(determinan matrix)

*   contoh matrix i baris pertama adalah kelipatan 2 dari matrix a
*   contoh matrix j kolom pertama adalah kelipatan 2 dari matrix a


In [10]:
print("Matriks A :")
print(a)
det = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(det.round())}")


print("\n")
print("Matriks I :")
print(i)
det1 = np.linalg.det(i)
print(f"Determinan dari Matriks I : {int(det1.round())}")
print("Matriks J :")
print(j)
detc = np.linalg.det(j)
print(f"Determinan dari Matriks I : {int(detc.round())}")


Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


Matriks I :
[[6 8]
 [2 1]]
Determinan dari Matriks I : -10
Matriks J :
[[6 4]
 [4 1]]
Determinan dari Matriks I : -10


##6. Jika suatu matrix yang berasal dari penjumlahan matrix k dengan matrix a maka untuk mencari determinan cukup menjumlahkan hasil dari 2 determinan matrix tersebut

In [11]:
print("Matriks K :")
print(k)
det = np.linalg.det(k)
print(f"Determinan dari Matriks k : {int(det.round())}")
print("   +")
print("Matriks L :")
print(l)
det1 = np.linalg.det(l)
print(f"Determinan dari Matriks L : {int(det1.round())}")
print("Hasill  : ")
print("Matriks A :")
print(a)
detc = np.linalg.det(a)
print(f"Determinan dari Matriks A : {int(detc.round())}")


Matriks K :
[[4 1]
 [2 1]]
Determinan dari Matriks k : 2
   +
Matriks L :
[[7 5]
 [2 1]]
Determinan dari Matriks L : -3
Hasill  : 
Matriks A :
[[3 4]
 [2 1]]
Determinan dari Matriks A : -5


## 7. Jika ada matrix segitiga atas atau bawah maka determinan nya adalah perkalian anggota diagonal matrix tersebut

In [12]:
print("Matriks Setiga atas :")
print(upper)
det = np.linalg.det(upper)
print(f"Determinan dari Matriks Setiga Atas : {int(det.round())}")


print("\n")
print("Matriks Setiga Bawah :")
print(lower)
det1 = np.linalg.det(lower)
print(f"Determinan dari Matriks Setiga Bawah : {int(det1.round())}")


Matriks Setiga atas :
[[1 2 3]
 [0 1 2]
 [0 0 1]]
Determinan dari Matriks Setiga Atas : 1


Matriks Setiga Bawah :
[[1 0 0]
 [1 2 0]
 [1 2 3]]
Determinan dari Matriks Setiga Bawah : 6


## 8. untuk mencari determinan dari Hasil perkalian matrix O dengan matrix p yaitu dengan mengalikan determinan matrix O dan p contoh (det O = 1 , det p = 1 maka det q adalah 0)

In [13]:
print("Matriks AAA :")
print(aaa)
det = np.linalg.det(aaa)
print(f"Determinan dari Matriks BBB : {int(det.round())}")
print("   x")
print("Matriks BBB :")
print(bbb)
det1 = np.linalg.det(bbb)
print(f"Determinan dari Matriks BBB : {int(det1.round())}")
print("Hasill  : ")
print("Matriks CCC :")
print(ccc)
detc = np.linalg.det(ccc)
print(f"Determinan dari Matriks CCC : {int(detc.round())}")


Matriks AAA :
[[2 1]
 [1 1]]
Determinan dari Matriks BBB : 1
   x
Matriks BBB :
[[1 1]
 [1 1]]
Determinan dari Matriks BBB : 0
Hasill  : 
Matriks CCC :
[[3 3]
 [2 2]]
Determinan dari Matriks CCC : 0
