# Aljabar Matriks
**tidak mengerjakan tidak boleh masuk**
- berikan penjelasan tentang apa itu matriks
- operasi matriks
- penjumlahan , perkalian, pengurangan transpose matriks
## Matrik

 matriks a dan c

In [ ]:
import numpy as np
a = np.array([[3,2,1],[1,2,3],[0,1,2]])
b = np.array([[1,2,3],[3,2,1],[0,1,2]])
c = np.array([[3,2],[2,3],[3,1]])
d = np.array([[4,5,6],[6,5,4],[0,1,2]])
e = a+b
f = 2*a
g = a@c
#print(d.shape)

#perkalian
a1 = a@b
a2 = b@c
h1 = a1@c
h2 = a@a2
print(c)
print(h2)



[[3 2]
 [2 3]
 [3 1]]
[[88 64]
 [72 52]
 [32 23]]


In [ ]:
#transpose
c1 = c.transpose()
cova = c1
cova

array([[3, 2, 3],
       [2, 3, 1]])

In [ ]:
covb = c@c1
covb

array([[13, 12, 11],
       [12, 13,  9],
       [11,  9, 10]])

CODING TUGAS

Matriks adalah kumpulan data yang disusun dalam bentuk persegi panjang atau persegi, diatur dalam baris dan kolom. Setiap elemen dalam matriks diberi indeks berdasarkan posisi baris dan kolomnya. Secara formal, sebuah matriks adalah array dua dimensi dari elemen-elemen, di mana setiap elemen memiliki dua indeks, satu untuk baris dan satu untuk kolom.

Secara umum, matriks sering digunakan untuk merepresentasikan data dalam berbagai konteks, termasuk matematika, ilmu komputer, teknik, fisika, dan lainnya. Contoh penggunaan matriks termasuk sistem persamaan linear, transformasi geometris, representasi data spasial, pengolahan citra, dan banyak lagi.

Misalnya, matriks \( A \) dengan ukuran \( m x n \) dapat ditulis sebagai:

\[ A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn}  \end{bmatrix} \]

Di sini, \( a_{ij} \)  adalah elemen matriks yang terletak pada baris ke-\( i \) dan kolom ke-\( j \).

Matriks dapat digunakan untuk melakukan berbagai operasi matematika, termasuk penambahan, pengurangan, perkalian, dan banyak lagi. Mereka adalah alat penting dalam berbagai bidang ilmu karena dapat merepresentasikan hubungan dan struktur data yang kompleks dengan cara yang sistematis dan terstruktur.

[refensi](https://staffnew.uny.ac.id/upload/198401312014042002/pendidikan/MATRIKS.pdf)


In [ ]:
#Penjumlahan pada matriks

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([6,5,4],[3,2,1]))
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[9,8,7],[3,2,1],[0,1,2]])


print(a+b)
print(c+d)

[[7 7 7]
 [7 7 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [3 2 1]
 [0 1 2]]
[[10 10 10]
 [ 7  7  7]
 [ 7  9 11]]


In [ ]:
#Pengurangan pada matriks

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([6,5,4],[3,2,1]))
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[9,8,7],[3,2,1],[0,1,2]])


print(a-b)
print(c-d)

[[-5 -3 -1]
 [ 1  3  5]]
[[-8 -6 -4]
 [ 1  3  5]
 [ 7  7  7]]


In [ ]:
#Perkalian pada matriks

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([6,5,4],[3,2,1]))
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[9,8,7],[3,2,1],[0,1,2]])


print(a@c)
print(c@d)

[[30 36 42]
 [66 81 96]]
[[15 15 15]
 [51 48 45]
 [87 81 75]]


In [ ]:
#Tranpose Matriks

def trans(a):
  b = a.transpose()
  cova = b
  return b

a = np.array([[1,2,3],[4,5,6]])

print('matriks sebelum di transpose')
print(a)
print()
print('matriks sesudah di transpose')
print(trans(a))

matriks sebelum di transpose
[[1 2 3]
 [4 5 6]]

matriks sesudah di transpose
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Perkalian matriks tangan menggunakan tool "@"

import numpy as np
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([6,5,4],[3,2,1]))
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[9,8,7],[3,2,1],[0,1,2]])

hasil = np.dot(c,d)
print(hasil)

[[15 15 15]
 [51 48 45]
 [87 81 75]]
