In [13]:
import numpy as np
print("pick col2")
a = np.array([[3,1,3],[2,1,2],[4,2,1]])
ai = np.linalg.inv(a)
print(a)
b = a[:2,2]
print(b)

pick col2
[[3 1 3]
 [2 1 2]
 [4 2 1]]
[3 2]


In [5]:
def minor(matrix, row, col):
    return [row[:col] + row[col+1:] for row in (matrix[:row] + matrix[row+1:])]

def determinant(matrix):
    if len(matrix) == 1:
        return matrix[0][0]
    elif len(matrix) == 2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    else:
        det = 0
        for col in range(len(matrix)):
            det += ((-1) ** col) * matrix[0][col] * determinant(minor(matrix, 0, col))
        return det

def transpose(matrix):
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

def inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Determinan nol, matriks tidak memiliki invers.")
    if len(matrix) == 1:
        return [[1/matrix[0][0]]]
    cofactors = []
    for i in range(len(matrix)):
        cofactor_row = []
        for j in range(len(matrix)):
            minor_mat = minor(matrix, i, j)
            cofactor_row.append(((-1) ** (i+j)) * determinant(minor_mat))
        cofactors.append(cofactor_row)
    adjugate = transpose(cofactors)
    inverse_matrix = [[adjugate[i][j] / det for j in range(len(adjugate))] for i in range(len(adjugate))]
    return inverse_matrix

# Contoh penggunaan:
matrix = [[3,1,3],
          [2,1,2],
          [4,2,1]]

print("Matriks:")
for row in matrix:
    print(row)

print("\nInvers Matriks:")
try:
    inv_matrix = inverse(matrix)
    for row in inv_matrix:
        print(row)
except ValueError as e:
    print(e)


Matriks:
[3, 1, 3]
[2, 1, 2]
[4, 2, 1]

Invers Matriks:
[1.0, -1.6666666666666667, 0.3333333333333333]
[-2.0, 3.0, -0.0]
[-0.0, 0.6666666666666666, -0.3333333333333333]


In [2]:
# Matriks contoh
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Mengambil elemen pada baris ke-2 dan kolom ke-3
elem = matrix[1][2]
print("Elemen pada baris ke-2 dan kolom ke-3:", elem)

# Menampilkan seluruh elemen matriks
print("\nSeluruh elemen matriks:")
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        print(matrix[i][j], end=" ")
    print()


Elemen pada baris ke-2 dan kolom ke-3: 6

Seluruh elemen matriks:
1 2 3 
4 5 6 
7 8 9 


In [4]:
import numpy as np

# Matriks contoh
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Mengambil elemen pada baris ke-2 dan kolom ke-3
elem = matrix[0, 2]
print("Elemen pada baris ke-2 dan kolom ke-3:", elem)

# Menampilkan seluruh elemen matriks
print("\nSeluruh elemen matriks:")
for row in matrix:
    for elem in row:
        print(elem, end=" ")
    print()


Elemen pada baris ke-2 dan kolom ke-3: 3

Seluruh elemen matriks:
1 2 3 
4 5 6 
7 8 9 


menghitung matriks 5x5



1.   menghitung matriks invers
2.   menghitung determinan mariks

